[package]
name = "filecoin-rs"
version = "0.1.0"
edition = "2021"
authors = ["Joshua Head <support@jeldonmusic.com>"]
description = "Filecoin integrations with Tauri UI"
repository = "https://github.com/jhead12"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]
path = "./src/lib.rs"

[[bin]]
name = "filecoin-rs"
path = "./src/main.rs" 

[dependencies]
cid = "0.11.1"
fvm_sdk = "4.0.0-alpha.4"
multihash-codetable = { version = "0.1.4", features = ["sha2"] }
anyhow = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4" # For async support
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
console_log = "1.0" # For console logging
log = "0.4" # For log::Level
libipld = "0.16" 
getrandom = { version = "0.3.2", features = ["wasm_js"], optional = true }
fvm_ipld_blockstore = { version = "0.3.1", optional = true }
fvm = { version = "4.6.0", optional = true }
fvm_shared = { version = "4.6.0", optional = true }
fvm_ipld_encoding = { version = "0.5.2", optional = true }
positioned-io = { version = "0.3", optional = true }
rig-core = { version = "0.2.1", optional = true }
arc = "0.0.1"
cocoa = "0.26.0"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
strip = "none"
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3

[features]
fvm_ipld_encoding = ["dep:fvm_ipld_encoding"]
fvm_shared = ["dep:fvm_shared"]
