# data_miner/src-tauri/Cargo.toml

[package]
name = "data-miner"
version = "0.1.0"
edition = "2021"



[dependencies]
tauri = { version = "2.0", features = ["devtools"], optional = true }
serde = { version = "1.0", features = ["derive"] }
filecoin-rs = { path = "../../filecoin-rs", features = ["native"], build = "wasm32-wasi" }  # Compile filecoin-rs to WASM using wasi target
tauri-specta = { version = "2.0.0-rc.21", features = ["typescript"] }
tokio= { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
tauri-plugin-window-state = { version = "0.1.0", optional = true }
tauri-plugin-upload = { version = "0.1.0", optional = true }
tauri-plugin-shell = { version = "0.1.0", optional = true }
tauri-plugin-opener = { version = "0.1.0", optional = true }
tauri-plugin-log = { version = "0.1.0", optional = true }


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
native = [
    "tauri",
    "tauri-plugin-window-state",
    "tauri-plugin-upload",
    "tauri-plugin-shell",
    "tauri-plugin-opener",
    "tauri-plugin-log",
  
]